# Generated by Django 5.2 on 2025-11-09 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='status',
            field=models.CharField(choices=[('init', 'Инициализирован'), ('in_progress', 'В процессе'), ('finished', 'Завершенный')], default='init', max_length=20),
        ),
    ]
