# Generated by Django 5.2 on 2026-02-12 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0011_alter_collectibleitem_name_alter_collectibleitem_uid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collectibleitem',
            old_name='picture',
            new_name='url',
        ),
    ]
