# Generated by Django 5.2 on 2026-02-12 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0012_rename_picture_collectibleitem_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectibleitem',
            name='uid',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
