# Generated by Django 5.2 on 2026-02-12 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0013_alter_collectibleitem_uid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collectibleitem',
            old_name='url',
            new_name='picture',
        ),
    ]
