# Generated by Django 5.2 on 2026-02-14 19:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0014_rename_url_collectibleitem_picture'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='collectibleitem',
            name='user_items',
            field=models.ManyToManyField(related_name='items', to=settings.AUTH_USER_MODEL),
        ),
    ]
