# Generated by Django 5.2 on 2026-03-13 21:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0016_alter_collectibleitem_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 13, 21, 5, 56, 718794, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='run',
            name='run_time_seconds',
            field=models.IntegerField(default=0),
        ),
    ]
