# Generated by Django 5.2 on 2026-03-14 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0019_alter_run_athlete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='date_time',
            field=models.DateTimeField(),
        ),
    ]
