# Generated by Django 5.2 on 2026-04-22 18:43

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0022_subscripe'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subscripe',
            unique_together={('coach', 'athlete')},
        ),
    ]
