# Generated by Django 5.2 on 2026-05-14 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0024_alter_challenge_athlete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='speed',
            field=models.FloatField(default=0, null=True),
        ),
    ]
