# Generated by Django 5.2 on 2026-05-16 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0028_alter_rating_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.FloatField(blank=True, choices=[(1.0, 1), (2.0, 2), (3.0, 3), (4.0, 4), (5.0, 5)], null=True),
        ),
    ]
